branch-defaults:
  main:
    environment: jeopardy
environment-defaults:
  jeopardy:
    branch: null
    repository: null
global:
  application_name: ndo-fullstack
  default_ec2_keyname: pliu-ndo-app
  default_platform: Node.js 24 running on 64bit Amazon Linux 2023
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
